backend:
  name: git-gateway
  branch: master
  accept_roles:
    - admin

publish_mode: editorial_workflow
media_folder: "src/posts/img" # Media files will be stored in the repo under images/uploads
collections:
  - name: "opus" # Used in routes, e.g., /admin/collections/blog
    label: "Opus" # Used in the UI
    folder: "src/posts" # The path to the folder where the documents are stored
    filter:
      field: category
      value: opus
    create: true # Allow users to create new documents in this collection
    delete: true
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Kategori", name: "category", widget: "hidden", default: "opus"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Opusnr.", name: "opus", widget: "string"}
      - {label: "Composed in year: ", name: "composedIn", widget: "string"}
      - {label: "Kort beskrivelse", name: "description", widget: "text"}
      - {label: "Image", name: "thumbnail", widget: "string"}
      - {label: "Instruments", name: "tags", widget: list, default: ['piano', 'sang']}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "artists" # Used in routes, e.g., /admin/collections/blog
    label: "Artists" # Used in the UI
    folder: "src/posts/artists" # The path to the folder where the documents are stored
    filter:
      field: category
      value: artister
    create: true # Allow users to create new documents in this collection
    delete: true
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Category", name: "category", widget: "hidden", default: "artister"}
      - {label: "Navn", name: "title", widget: "string"}
      - {label: "Image", name: "thumbnail", widget: "string"}
      - {label: "Instrument", name: "tags", widget: list, default: ['piano']}
      - {label: "Body", name: "body", widget: "markdown"}
